# Generated by Django 2.2.5 on 2020-03-18 04:39

from django.db import migrations, models
import scenarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_intervaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervaldata',
            name='interval_data_file',
            field=models.FileField(upload_to=scenarios.models.content_file_name),
        ),
    ]
