# Generated by Django 2.2.5 on 2020-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='chosen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
