# Generated by Django 2.2.5 on 2020-09-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('scenarios', '0005_scenario_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingHourDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_type', models.CharField(max_length=25)),
                ('monday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('monday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('monday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('monday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('tuesday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('tuesday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('tuesday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('tuesday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('wednesday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('wednesday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('wednesday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('wednesday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('thursday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('thursday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('thursday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('thursday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('friday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('friday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('friday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('friday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('saturday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('saturday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('saturday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('saturday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('sunday_lighting_hour_1_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('sunday_lighting_hour_1_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('sunday_lighting_hour_2_start', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('sunday_lighting_hour_2_end', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='N/A', max_length=15)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'unique_together': {('scenario', 'lighting_type')},
            },
        ),
        migrations.CreateModel(
            name='LightingOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lights', models.IntegerField()),
                ('maintenance_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustments_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verdia_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verdia_fee_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustments_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LightingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_existing_luminaire', models.IntegerField()),
                ('existing_luminaire_power', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number_of_replaced_luminaire', models.IntegerField()),
                ('replacement_luminaire_power', models.DecimalField(decimal_places=1, max_digits=8)),
                ('power_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_operating_hours', models.IntegerField()),
                ('total_estimated_savings_kwhs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veec_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esc_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dollar_per_fixture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labour_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixtures_per_hour', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('led_life_in_months', models.IntegerField()),
                ('existing_lamp_replacement_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existing_luminaire_life_in_months', models.IntegerField()),
                ('existing_luminaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.ExistingLight')),
                ('lighting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting.LightingHourDetail')),
                ('replacement_luminaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.LedLight')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
