# Generated by Django 2.2.5 on 2020-03-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('lighting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lightinghourdetail',
            unique_together={('scenario', 'lighting_type')},
        ),
    ]
