# Generated by Django 2.2.5 on 2020-03-19 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_auto_20200305_1214'),
        ('scenarios', '0003_auto_20200318_1439'),
        ('lighting', '0002_auto_20200318_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('number_of_existing_lights', models.IntegerField()),
                ('existing_luminaire_power', models.DecimalField(decimal_places=1, max_digits=5)),
                ('number_of_replaced_luminaire', models.IntegerField()),
                ('replacement_luminaire_power', models.DecimalField(decimal_places=1, max_digits=5)),
                ('power_reduction', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_operating_hours', models.IntegerField()),
                ('total_estimated_savings_kwhs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veec_discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esc_discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_adjustment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maintenance_savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dollar_per_fixture', models.DecimalField(decimal_places=2, max_digits=6)),
                ('labour_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fixtures_per_hour', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('led_life_in_months', models.IntegerField()),
                ('existing_lamp_replacement_costs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('existing_luminaire_life_in_months', models.IntegerField()),
                ('existing_luminaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.ExistingLight')),
                ('lighting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lighting.LightingHourDetail')),
                ('replacement_luminaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.LedLight')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
