# Generated by Django 2.2.5 on 2020-03-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0003_lightinginput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightinginput',
            old_name='number_of_existing_lights',
            new_name='number_of_existing_luminaire',
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
