# Generated by Django 2.2.5 on 2020-03-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('lighting', '0004_auto_20200324_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lights', models.IntegerField()),
                ('maintenance_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustments_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verdia_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verdia_fee_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustments_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
