# Generated by Django 2.2.5 on 2020-04-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0005_lightingoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightinginput',
            name='discount_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='dollar_per_fixture',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='esc_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='existing_lamp_replacement_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='existing_luminaire_power',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='labour_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='maintenance_savings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='power_reduction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='replacement_luminaire_power',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lightinginput',
            name='veec_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
