# Generated by Django 2.2.5 on 2020-03-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_billdetail_kwhs_consumed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billdetail',
            options={'ordering': ('id',)},
        ),
    ]
