# Generated by Django 2.2.5 on 2020-03-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('inputs', '0004_operatinghourdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_period_1_start_date', models.IntegerField()),
                ('holiday_period_1_start_month', models.IntegerField()),
                ('holiday_period_1_end_date', models.IntegerField()),
                ('holiday_period_1_end_month', models.IntegerField()),
                ('holiday_period_2_start_date', models.IntegerField()),
                ('holiday_period_2_start_month', models.IntegerField()),
                ('holiday_period_2_end_date', models.IntegerField()),
                ('holiday_period_2_end_month', models.IntegerField()),
                ('holiday_period_3_start_date', models.IntegerField()),
                ('holiday_period_3_start_month', models.IntegerField()),
                ('holiday_period_3_end_date', models.IntegerField()),
                ('holiday_period_3_end_month', models.IntegerField()),
                ('holiday_period_4_start_date', models.IntegerField()),
                ('holiday_period_4_start_month', models.IntegerField()),
                ('holiday_period_4_end_date', models.IntegerField()),
                ('holiday_period_4_end_month', models.IntegerField()),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
