# Generated by Django 2.2.5 on 2020-03-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_holidaydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_1_end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_1_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_1_start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_1_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_2_end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_2_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_2_start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_2_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_3_end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_3_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_3_start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_3_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_4_end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_4_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_4_start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaydetail',
            name='holiday_period_4_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
