# Generated by Django 2.2.5 on 2020-03-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('inputs', '0006_auto_20200311_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceForecastOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2019', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2020', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2021', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2022', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2025', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2026', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_2027', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
