# Generated by Django 2.2.5 on 2020-03-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('inputs', '0007_priceforecastoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationsOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_1', models.IntegerField(blank=True, null=True)),
                ('override_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_2', models.IntegerField(blank=True, null=True)),
                ('override_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_3', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_3', models.IntegerField(blank=True, null=True)),
                ('override_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_4', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_4', models.IntegerField(blank=True, null=True)),
                ('override_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_5', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_5', models.IntegerField(blank=True, null=True)),
                ('override_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month_6', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('year_6', models.IntegerField(blank=True, null=True)),
                ('override_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
