# Generated by Django 2.2.5 on 2020-03-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        ('inputs', '0008_escalationsoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_solar_export', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('year_2019', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2020', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2021', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2022', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2023', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2024', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2025', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2026', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2027', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2028', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2029', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2030', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year_2031', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
