# Generated by Django 2.2.5 on 2020-03-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=15)),
                ('include', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tariff_type', models.CharField(choices=[('Peak', 'Peak'), ('Offpeak', 'Offpeak'), ('Flat', 'Flat')], max_length=10)),
                ('weekday_start_time', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=10)),
                ('weekday_end_time', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=10)),
                ('weekend_start_time', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=10)),
                ('weekend_end_time', models.CharField(choices=[('All Times', 'All Times'), ('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=10)),
                ('months', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Retail', 'Retail'), ('Network', 'Network'), ('Marketing', 'Marketing'), ('Environmental', 'Environmental'), ('Metering', 'Metering'), ('Others', 'Others')], max_length=10)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
