# Generated by Django 2.2.5 on 2020-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbillinputs', '0003_fixedcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycharge',
            name='category',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Network', 'Network'), ('Marketing', 'Marketing'), ('Environmental', 'Environmental'), ('Metering', 'Metering'), ('Others', 'Others')], max_length=20),
        ),
    ]
