# Generated by Django 2.2.5 on 2020-04-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('powerbillinputs', '0004_auto_20200408_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demandcharge',
            unique_together={('scenario', 'tariff_name')},
        ),
        migrations.AlterUniqueTogether(
            name='energycharge',
            unique_together={('scenario', 'tariff_name')},
        ),
        migrations.AlterUniqueTogether(
            name='fixedcharge',
            unique_together={('scenario', 'tariff_name')},
        ),
    ]
