# Generated by Django 2.2.5 on 2020-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbillinputs', '0005_auto_20200408_1439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demandcharge',
            unique_together=set(),
        ),
    ]
