# Generated by Django 2.2.5 on 2020-03-25 23:21

from django.db import migrations, models
import django.db.models.deletion
import solarpfc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('solar_layout_file', models.FileField(upload_to=solarpfc.models.layout_file_name)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
