# Generated by Django 2.2.5 on 2020-03-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('solarpfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solarlayout',
            unique_together={('scenario', 'file_name')},
        ),
    ]
