# Generated by Django 2.2.5 on 2020-03-30 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('solarpfc', '0002_auto_20200326_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('solar_unit_cost', models.DecimalField(decimal_places=3, max_digits=5)),
                ('solar_unit_cost_override', models.DecimalField(decimal_places=3, max_digits=5)),
                ('gross_system_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_adjustments_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verdia_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verdia_fee_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustments_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_type', models.CharField(choices=[('STC', 'STC'), ('LGC', 'LGC')], max_length=5)),
                ('system_type_override', models.CharField(choices=[('No override', 'No Override'), ('LGC', 'LGC')], max_length=15)),
                ('stc_deeming_period', models.IntegerField()),
                ('stc_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_unit_cost', models.DecimalField(decimal_places=3, max_digits=5)),
                ('maintenance_cost_per_annum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('include_solar_maintenance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
