# Generated by Django 2.2.5 on 2020-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpfc', '0003_solarcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarcost',
            name='system_type',
            field=models.CharField(max_length=5),
        ),
    ]
