# Generated by Django 2.2.5 on 2020-03-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('solarpfc', '0004_auto_20200330_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolarCost',
            new_name='SolarPrice',
        ),
    ]
