# Generated by Django 2.2.5 on 2020-03-31 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('solarpfc', '0006_auto_20200331_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfc_size', models.IntegerField()),
                ('pfc_unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pfc_unit_cost_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gross_system_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verdia_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verdia_fee_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_unit_cost', models.DecimalField(decimal_places=3, max_digits=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
