# Generated by Django 2.2.5 on 2020-03-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50, unique=True)),
                ('salesforce_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
