# Generated by Django 2.2.5 on 2020-07-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200306_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('num_led', models.IntegerField()),
                ('pfc_size', models.IntegerField()),
                ('num_sites', models.IntegerField()),
                ('savings_yr_1_dollar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('savings_yr_1_energy', models.DecimalField(decimal_places=3, max_digits=20)),
                ('npv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irr', models.DecimalField(decimal_places=4, max_digits=6)),
                ('payback', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lcoe', models.DecimalField(decimal_places=4, max_digits=5)),
                ('base_load_kwh', models.DecimalField(decimal_places=3, max_digits=20)),
                ('electricity_current_bill', models.DecimalField(decimal_places=2, max_digits=20)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
