# Generated by Django 2.2.5 on 2020-08-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashflow_start_month', models.IntegerField()),
                ('cashflow_start_year', models.IntegerField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
