# Generated by Django 2.2.5 on 2020-03-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_lighting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('solar_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pfc_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_pf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interval_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scenarios.IntervalData')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
