# Generated by Django 2.2.5 on 2020-06-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200318_1439'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irr', models.DecimalField(decimal_places=4, max_digits=6)),
                ('payback', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lcoe', models.DecimalField(decimal_places=4, max_digits=5)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
