# Generated by Django 2.2.5 on 2020-06-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_simulationoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationoutput',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario'),
        ),
    ]
