# Generated by Django 2.2.5 on 2020-03-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Industry_type',
            new_name='industry_type',
        ),
    ]
