# Generated by Django 2.2.5 on 2020-03-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200306_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('new_south_wales', 'New South Wales'), ('northern_territory', 'Northern Territory'), ('queensland', 'Queensland'), ('victoria', 'Victoria'), ('south_australia', 'South Australia'), ('australian_capital_territory', 'Australian Capital Territory'), ('tasmania', 'Tasmania'), ('western_australia', 'Western Australia')], max_length=20),
        ),
    ]
