# Generated by Django 2.2.5 on 2020-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200318_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='included',
            field=models.BooleanField(default=True),
        ),
    ]
