from rest_framework import serializers

class SolarPriceSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    scenario_id = serializers.PrimaryKeyRelatedField(many=False, read_only=True)
    scenario_name = serializers.StringRelatedField(many=False, read_only=True)
    solar_size = serializers.DecimalField(max_digits=10, decimal_places=3)
    solar_unit_cost = serializers.DecimalField(max_digits=5, decimal_places=3)
    solar_unit_cost_override = serializers.DecimalField(max_digits=5, decimal_places=3)
    gross_system_cost = serializers.DecimalField(max_digits=12 ,decimal_places=2)
    other_adjustments_1 = serializers.DecimalField(max_digits=10 ,decimal_places=2)
    verdia_fee = serializers.DecimalField(max_digits=5 ,decimal_places=2)
    verdia_fee_dollars = serializers.DecimalField(max_digits=10 ,decimal_places=2)
    other_adjustments_2 = serializers.DecimalField(max_digits=10 ,decimal_places=2)
    system_type = serializers.CharField(max_length=5)
    system_type_override = serializers.CharField(max_length=15)
    stc_deeming_period = serializers.IntegerField()
    stc_discount = serializers.DecimalField(max_digits=10, decimal_places=2)
    system_cost = serializers.DecimalField(max_digits=12,decimal_places=2)
    system_unit_cost = serializers.DecimalField(max_digits=5, decimal_places=3)
    maintenance_cost_per_annum = serializers.DecimalField(max_digits=10,decimal_places=2)
    include_solar_maintenance = serializers.CharField(max_length=5)

class PFCPriceSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    scenario_id = serializers.PrimaryKeyRelatedField(many=False, read_only=True)
    scenario_name = serializers.StringRelatedField(many=False, read_only=True)
    pfc_size = serializers.IntegerField()
    pfc_unit_cost = serializers.DecimalField(max_digits=6, decimal_places=2)
    pfc_unit_cost_override = serializers.DecimalField(max_digits=6, decimal_places=2)
    gross_system_cost = serializers.DecimalField(max_digits=12 ,decimal_places=2)    
    verdia_fee = serializers.DecimalField(max_digits=5 ,decimal_places=2)
    verdia_fee_dollars = serializers.DecimalField(max_digits=10 ,decimal_places=2)    
    system_cost = serializers.DecimalField(max_digits=12,decimal_places=2)
    system_unit_cost = serializers.DecimalField(max_digits=5, decimal_places=3)