# Generated by Django 2.2.5 on 2020-02-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffEscalations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('queensland', models.DecimalField(decimal_places=3, max_digits=4)),
                ('new_south_wales', models.DecimalField(decimal_places=3, max_digits=4)),
                ('victoria', models.DecimalField(decimal_places=3, max_digits=4)),
                ('south_australia', models.DecimalField(decimal_places=3, max_digits=4)),
                ('western_australia', models.DecimalField(decimal_places=3, max_digits=4)),
                ('australian_capital_territory', models.DecimalField(decimal_places=3, max_digits=4)),
                ('tasmania', models.DecimalField(decimal_places=3, max_digits=4)),
                ('northern_territory', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
