# Generated by Django 2.2.5 on 2020-02-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_offpeakenergyrates_peakenergyrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='australian_capital_territory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='new_south_wales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='northern_territory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='queensland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='south_australia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='tasmania',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='victoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offpeakenergyrates',
            name='western_australia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='australian_capital_territory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='new_south_wales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='northern_territory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='queensland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='south_australia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='tasmania',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='victoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='peakenergyrates',
            name='western_australia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
