# Generated by Django 2.2.5 on 2020-02-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20200226_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LedLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('fitting_type', models.CharField(choices=[('BT', 'Batten'), ('BH', 'Bulkhead'), ('DL', 'Downlight'), ('DE', 'Decorative'), ('FL', 'Floodlight'), ('HB', 'Highbay'), ('OT', 'Other'), ('OY', 'Oyster'), ('PN', 'Panel'), ('WP', 'Weatherproof')], max_length=2)),
                ('installation_type', models.CharField(choices=[('RP', 'Recessed Plaster'), ('RTG', 'Recessed T-Grid'), ('SM', 'Surface Mount'), ('SUS', 'Suspended'), ('WM', 'Wall Mount'), ('OIT', 'Other')], max_length=2)),
            ],
        ),
    ]
