# Generated by Django 2.2.5 on 2020-02-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_existinglight_ledlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledlight',
            name='replacement_fitting_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledlight',
            name='replacement_fittings_per_hour',
            field=models.IntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledlight',
            name='system_power',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledlight',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
