# Generated by Django 2.2.5 on 2020-02-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20200227_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='existinglight',
            name='fitting_type',
            field=models.CharField(choices=[('BT', 'Batten'), ('BH', 'Bulkhead'), ('DL', 'Downlight'), ('DE', 'Decorative'), ('EB', 'Emergency Batten'), ('FL', 'Floodlight'), ('HB', 'Highbay'), ('OT', 'Other'), ('OY', 'Oyster'), ('TR', 'Troffer'), ('PN', 'Panel'), ('WP', 'Weatherproof')], default='BT', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='installation_type',
            field=models.CharField(choices=[('RP', 'Recessed Plaster'), ('RTG', 'Recessed T-Grid'), ('SM', 'Surface Mount'), ('SUS', 'Suspended'), ('WM', 'Wall Mount'), ('OIT', 'Other')], default='SUS', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='lamp_life',
            field=models.IntegerField(default=10000, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='lamp_quantity',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='lamp_wattage',
            field=models.DecimalField(decimal_places=1, default=150, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='name',
            field=models.CharField(default='', max_length=45, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='other_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='existinglight',
            name='replacement_fitting_price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='replacement_fittings_per_hour',
            field=models.IntegerField(default=4, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='replacement_lamp_fittings_per_hour',
            field=models.IntegerField(default=4, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='replacement_lamp_price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existinglight',
            name='system_power',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledlight',
            name='led_life',
            field=models.IntegerField(default=50000, max_length=6),
            preserve_default=False,
        ),
    ]
