# Generated by Django 2.2.5 on 2020-02-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20200227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existinglight',
            name='lamp_life',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='existinglight',
            name='lamp_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='existinglight',
            name='replacement_fittings_per_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='existinglight',
            name='replacement_lamp_fittings_per_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledlight',
            name='led_life',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledlight',
            name='replacement_fittings_per_hour',
            field=models.IntegerField(),
        ),
    ]
