# Generated by Django 2.2.5 on 2020-02-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20200227_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledlight',
            options={'ordering': ('name',)},
        ),
    ]
