# Generated by Django 2.2.5 on 2020-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20200227_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existinglight',
            name='other_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
