# Generated by Django 2.2.5 on 2020-02-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_auto_20200228_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='existinglight',
            name='led_light',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='existing_lights', to='references.LedLight'),
            preserve_default=False,
        ),
    ]
