# Generated by Django 2.2.5 on 2020-03-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_auto_20200302_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledlight',
            name='installation_type',
            field=models.CharField(choices=[('Recessed Plaster', 'Recessed Plaster'), ('Recessed T-Grid', 'Recessed T-Grid'), ('Surface Mount', 'Surface Mount'), ('Suspended', 'Suspended'), ('Wall Mount', 'Wall Mount'), ('Other', 'Other')], max_length=2),
        ),
    ]
