# Generated by Django 2.2.5 on 2020-03-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_solarcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarcost',
            old_name='multiple_site_dollar_per_watt',
            new_name='multi_site_dollar_per_watt',
        ),
        migrations.RenameField(
            model_name='solarcost',
            old_name='multiple_site_verdia_fee',
            new_name='multi_site_verdia_fee',
        ),
    ]
