# Generated by Django 2.2.5 on 2020-03-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0017_auto_20200303_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFCCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfc_rating', models.IntegerField(unique=True)),
                ('pfc_dollar_per_kvar', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
