# Generated by Django 2.2.5 on 2020-03-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_pfccost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfccost',
            options={'ordering': ('pfc_rating',)},
        ),
        migrations.AlterModelOptions(
            name='solarcost',
            options={'ordering': ('system_size',)},
        ),
    ]
