# Generated by Django 2.2.5 on 2020-03-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_auto_20200305_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField()),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('new_south_wales', 'New South Wales'), ('northern_territory', 'Northern Territory'), ('queensland', 'Queensland'), ('victoria', 'Victoria'), ('south_australia', 'South Australia'), ('australian_capital_territory', 'Australian Capital Territory'), ('tasmania', 'Tasmania'), ('western_australia', 'Western Australia')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('emissions_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('stc_zone', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('pvsyst_generation_factor', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'unique_together': {('postcode', 'suburb')},
            },
        ),
    ]
