# Generated by Django 2.2.5 on 2020-03-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_postcoderesource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcoderesource',
            options={'ordering': ('postcode', 'suburb')},
        ),
    ]
