# Generated by Django 2.2.5 on 2020-03-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0021_auto_20200326_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdia_fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
