# Generated by Django 2.2.5 on 2020-09-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_solardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcoderesource',
            name='state',
            field=models.CharField(choices=[('new_south_wales', 'New South Wales'), ('northern_territory', 'Northern Territory'), ('queensland', 'Queensland'), ('victoria', 'Victoria'), ('south_australia', 'South Australia'), ('australian_capital_territory', 'Australian Capital Territory'), ('tasmania', 'Tasmania'), ('western_australia', 'Western Australia')], max_length=100),
        ),
    ]
